### ISSUE TITLE
Image y coord doesnt get recognized correctly

### ISSUE THREAD

**Issue by Xinoi** [Xinoi/DNASIC#21]
I added the function to click on the level images, but it only checkes the top half of the picture and above. I guess it gets the wrong coords because of spacing or smthg. Issue:
![grafik](https://user-images.githubusercontent.com/91490471/168314161-2e7d98f2-0035-4f03-8068-479e8a273731.png)

**Comment by Jan130** [comment]
Fixed this in a new commit by using a ClickListener instead of checking for clicks manually.

**Comment by Xinoi** [comment]
I tired a click listener before but it somehow didn't work lol

**Comment by Jan130** [comment]
Now it does xD
