### ISSUE TITLE
Settings.json

### ISSUE THREAD

**Issue by Xinoi** [Xinoi/DNASIC#25]
the Game creates an extra assets folder in the already existing assets folder and saves the game files there (settings.json, GameData)

possible Solution:
-> remove assets/ prefix from the Gdx.files.local paths | apparently doesn't work on Jans Pc -> maybe change .local to .internal

**Comment by Xinoi** [comment]
try changing it to ...files.internal("settings.json") and ...files.internal("GameData/...")

**Comment by Jan130** [comment]
Yeah but I don't understand why it creates a new folder on your PC...

**Comment by Jan130** [comment]
I tried it again and it works normally on my computer

**Comment by Xinoi** [comment]
aight
