### ISSUE TITLE
Main Menu Music

### ISSUE THREAD

**Issue by Xinoi** [Xinoi/DNASIC#26]
i think it is a good idea to use the main menu music (Rebel?) in all Menu Screens(level, settings) cause it sounds hella fire and it is smoother. Other games usually have only one menu music too

**Comment by Xinoi** [comment]
it kinda disturbs the flow to have 2 different songs

**Comment by itsSanoi** [comment]
That is a good pint but the music is insane we have to use the music in a other part of the game

**Comment by Jan130** [comment]
Good point. I might implement some kind of audio player later so the song doesn't restart every time you switch screens.

**Comment by itsSanoi** [comment]
i think that shuld fix it

**Comment by Xinoi** [comment]
its probably possible without some extra player. I had an issue that the music kept playing even though i changed screen. I fixed it by stopping it in the hide() method. If we dont do that we simply have to stat the music in the main menu Screen and dont even have to create new Music objects and playing them in other screens

**Comment by Xinoi** [comment]
but i guess an audio manager is the more sublime solution

**Comment by Jan130** [comment]
> its probably possible without some extra player. I had an issue that the music kept playing even though i changed screen. I fixed it by stopping it in the hide() method. If we dont do that we simply have to stat the music in the main menu Screen and dont even have to create new Music objects and playing them in other screens

The problem with this is that we will not be able to stop the music later since the object we would need to use would be on another screen...

**Comment by Jan130** [comment]
Just tried implementig it on a new branch but couldn't get it to work. If anybody has a good idea how to get it to work you could just try :-)

**Comment by Xinoi** [comment]
what did you try ?

**Comment by Jan130** [comment]
I tried creating a MusicPlayer class and creating an instance of it in the Game class and calling the methods from the screens, but the music didn't play.

**Comment by Xinoi** [comment]
K im gonna try creating a music player too later
