### ISSUE TITLE
Move variables to Game class

### ISSUE THREAD

**Issue by Jan130** [Xinoi/DNASIC#28]
Do you think that it would make sense to move certain variables like font and clickSound which are instantiated in multiple classes to the DNASIC class and just reuse the same instance every time?

**Comment by Xinoi** [comment]
yup

**Comment by Xinoi** [comment]
thats a good idea

**Comment by itsSanoi** [comment]
i think that makes senese.

**Comment by itsSanoi** [comment]
but maby we shuld show that in the nae of the variable (pubic int test -> public int globTest)

**Comment by itsSanoi** [comment]
but maby we shuld show that in the nae of the variable (pubic int test -> public int globTest)

**Comment by Jan130** [comment]
I wouldn't do so because it's pretty obvious because you would have to do something like `DNASI.INSTANCE.font` to access it.

**Comment by itsSanoi** [comment]
thats right

**Comment by Xinoi** [comment]
done
