### ISSUE TITLE
Meilenstein Vorschläge

### ISSUE THREAD

**Issue by Xinoi** [Xinoi/DNASIC#31]
Hier ein paar Vorschläge, was wir für Meilensteine nehmen könnten. Vorschläge sind erwünscht:
1. Spielkonzept
2. Projekt-Planung und Arbeitseinteilung
3. Fertigstellung des Grundspiels für ersten Release (Ich glaub es wäre ne Coole Idee, wenn wir die Release-funktion von Github-Nutzen)
4. (Erweiterung mit Wunschkonzepten)
5. Bug-Testen
6. Veröffentlichung des 1.0 Releases

**Comment by Jan130** [comment]
Ich würde Projekt-Planung und Arbeitseinteilung fast weglassen, weil das ja eigentlich das ist wofür das Pflichtenheft da ist oder?

**Comment by Xinoi** [comment]
ok ich würd die Fertigstellung des Grundspiels auch noch aufteilen

**Comment by Jan130** [comment]
Basierend auf @Xinoi's Vorschlägen:

1. Letzte Details des Spielkonzepts erarbeitet
2. Spiellogik abgeschlossen
3. Fertigstellung des ersten Levels + erster Release
4. Hinzufügen von Leveln
5. Hinzufügen von Wunschkriterien
6. Testen (evtl. durch externe Leute?) und Optimieren
7. Veröffentlichen des Release 1.0

**Comment by Xinoi** [comment]
dann übernehm ich die mal so ins Pflichtenheft

**Comment by Xinoi** [comment]
passt das der commit ?

**Comment by Jan130** [comment]
Hab noch ein bisschen was angepasst und ein Bild reingemacht ihr könnte euch mal das PDF anschauen

**Comment by Xinoi** [comment]
an der Arbeitsteilung müssen wir noch arbeiten aber sonst passt es denke ich

**Comment by Jan130** [comment]
Arbeitsteilung würde ich in ein neues issue machen, falls wir da noch was diskutieren müssen.
