### ISSUE TITLE
more packages

### ISSUE THREAD

**Issue by Xinoi** [Xinoi/DNASIC#33]
should we make more packages like: de.jjj.dnasic.main / de.jjj.dnasic.screens / etc to make the structure clearer ?

**Comment by Jan130** [comment]
Yes, good idea

**Comment by Jan130** [comment]
Should I do that?

**Comment by Xinoi** [comment]
Yes right now I have no time

**Comment by Jan130** [comment]
I added a screens package in 276b289d944e05b9998d64e9cdeb271f8dc3465f. Is there anything else we need right now? In case we need anything else later on we can just add it when we need it...

**Comment by Xinoi** [comment]
mabye a package where the player and enemy ship classes are stored

**Comment by Jan130** [comment]
Added this
