### ISSUE TITLE
Move to Github Project?

### ISSUE THREAD

**Issue by Jan130** [Xinoi/DNASIC#35]
Should we move our backlog, etc. from Trello to a Github project?

# Pro
- everything in one place
- possibility of prioritizing tasks
- possibility of linking issues and pull requests with tasks on the board
# Con
- we would have to move everything over

If we wanted to do so, I think @Xinoi would have to create the project.

**Comment by Xinoi** [comment]
i agree with that idea. right now we have not too much tasks in trello so it might be not too much work. The option too link issues and merges with it is also pretty usefull and u dont have to check 2 websites at once.

**Comment by Xinoi** [comment]
if @itsSanoi agrees i could create that

**Comment by Xinoi** [comment]
another question would be what format or template we use.

**Comment by Jan130** [comment]
I'm not really too deep into this topic so I have no idea which exist.

**Comment by Jan130** [comment]
Von would probably also be that there is no mobile app for projects... And I don't think that you can access them via the Github android app

**Comment by Xinoi** [comment]
I created a Project. It looks like Trello and we could start moving the content

**Comment by Jan130** [comment]
Did you add us to the Project?

**Comment by Xinoi** [comment]
I invited you now
