### ISSUE TITLE
Unterkategorien in Projects

### ISSUE THREAD

**Issue by Xinoi** [Xinoi/DNASIC#43]
**Ist es möglich, einen Task einer bestimmten Kategorie zuzuweisen?**
Ich habe den Level 1 Task überarbeitet und es ist dabei klar geworden, dass wir alle Aufgaben dafür nicht in einem Merge schaffen können.
Daher ist meine Frage, ob es möglich ist, die Checkliste, die im Level 1 **_Task steht in verschiedene Task aufzuteilen, die jedoch alle zu einer Kategorie gehören._**
Das wäre auch bei anderen größeren Aufgaben sehr nützlich.
Wenn das jedoch nicht von GitHub selber aus möglich ist, gäbe es zwei andere Optionen:

1. Einen Task mit Checkliste (wie jetzt), den wir immer wieder zurück in den Backlog schieben, sobald etwas erledigt ist
2. Die Checkliste in einzelne Tasks aufteilen und die Kategorie vieleicht durch eine manuelle Kennzeichnung deutlich machen 
_`Bsp: Collision Detection (Level 1)`_

_Ich persönlich wäre eher für Option 2_

**Comment by Jan130** [comment]
Also mir würden spontan ein paar Versionen einfallen:
1. Wir könnten einfach einen Meilenstein benutzen und die einzelnen Aufgaben als Issues dazu hinzufügen.
2. Wir könnten jeden Task als Issue erstellen und über Links in die Checkliste einfügen
3. Wir könnten theoretisch Tags oder sowas verwenden

**Comment by Jan130** [comment]
Ich habe noch was anderes gefunden: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists
Das scheint so ungefähr das zu sein was ich bei Nummer 2 geschrieben habe.

**Comment by Jan130** [comment]
Also müsste man theoretisch wenn man aus dem Draft für Level 1 ein Issue macht das so machen können wie die in dem Link schreiben.

**Comment by Xinoi** [comment]
**zu deinen Möglichkeiten:**

> 1. Könnte eine gute Idee sein, ich weiß jedoch nicht ob ddas der Sinn von Meilensteinen ist (ist aber eigentlcih ja auch egal).
> 2. Ich glaube das würde zu viele issues ergeben und wir hätten keinen Überblick mehr über wirkliche "Issues". Außerdem würde der Sinn des Projects teilweise verloren gehen
> 3. Ich bin mir nicht sicher wie das funktioniert und es scheint ziemlich umständlich

_Ich glaub die einfachste und praktischste Lösung ist das mit den Meilensteinen. (Wir müssen den vorhergesehenen Sinn ja nicht befolgen)_

**Comment by Xinoi** [comment]
Issues wäre aber auch keine schlechte Idee, da diese immer automatisch mit dem Project aktualisiert werden. Man würde auch den Überblick behalten können, wenn wir die Labels noch mehr nutzen

**Comment by Jan130** [comment]
Ich wäre für die Version mit den Issues, da ist es glaub ich am besten verlinkt und die Issues werden automatisch geupdated und so.
Wie siehts denn mit @itsSanoi aus?

**Comment by Xinoi** [comment]
Gut dann nehmen wir die issue Lösung
Ich werde mal ein Issue dafür erstellen xD
