### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Xinoi** [Xinoi/DNASIC#45]
I think it would be beneficial (and cool) to choose a license for our little project. The question is which one. There are quite a few and i dont know which one is the most fitting for our project.

**Comment by itsSanoi** [comment]
what is a license?

**Comment by Xinoi** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by Xinoi** [comment]
`https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633`
I think this gives a good oversight over the licenses

**Comment by Jan130** [comment]
My personal favourite would be the GPL one

**Comment by itsSanoi** [comment]
If you want you can add a LIicense. You can chose whats  your faforite. i dont realy worry. But i personaly dont see the advatages of a licanse. Baut do what you think is right i dont care

**Comment by Xinoi** [comment]
Im going to choose a GPL one then
