### ISSUE TITLE
Double Musik

### ISSUE THREAD

**Issue by itsSanoi** [Xinoi/DNASIC#83]
Wenn mann in der Upgrade Page (du kommst dahin indem du in das Level 1 gehst und "u" drückst) spielt die Musik doppelt. Weiß nicht was ich falsch gemacht habe

**Comment by Jan130** [comment]
Schaue ich mir mal an wenn ich Zeit habe

**Comment by Jan130** [comment]
Gefixed in fdc02a4aa6eab1e4c428babd623480261cf45534
