### ISSUE TITLE
Left click or Space

### ISSUE THREAD

**Issue by Xinoi** [Xinoi/DNASIC#91]
@itsSanoi wanted to shoot with the left click on the mouse. So now you can shoot with both but the shoot rate is doubled. There are two ways to fix it:
1. add a shoot delay (may be better if we implement a shoot rate to upgrade -> holdding Space should shoot in a fixed pattern)
2. add the option in the settigns to choose between the keys (@Jan130 has to do this because he knows how to save progress)
Implementing both would be beneficial cause i want to implement the shoot rate and the settings need some more content .)

**Comment by Jan130** [comment]
I already implemented the second point on the leftClickShoot branch

**Comment by Jan130** [comment]
Implemented the first point to as a reload time for weapons (works for enemies as well as the player).
